### ISSUE TITLE
Allow configuration with own GitLab instance

### ISSUE THREAD

**Issue by illonis** [SocialiteProviders/GitLab#2]
I use a GitLab CE installation on my own server, thus the API-Url base is not the original _gitlab.com_ one.
A configuration option for a custom base-url would be really nice.

**Comment by DraperStudio** [comment]
I pushed https://github.com/SocialiteProviders/GitLab/commit/1c2ef6683a933d8f2b3d1429f895c2945333d0a1 and tagged `v2.0.1` so you should be able to set `GITLAB_INSTANCE_URI=http://gitlab.mydomain.xyz/` in your `.env` file now.
